Update hosting-on-firebase.md
gohugoio/hugoDocs pull request #1347
Opened 2021-02-28 22:59 UTC by bggo

Firebase now does support native integration with Github Actions for CICD. Including steps on this documentation.

2021-02-28 23:35 UTC, coliff commented on content/en/hosting-and-deployment/hosting-on-firebase.md
> +## Using Firebase & Github CI/CD
Github should be GitHub

2021-02-28 23:35 UTC, coliff commented on content/en/hosting-and-deployment/hosting-on-firebase.md
> +In new versions of firebase, some other questions apply:
Capitalize Firebase

2021-02-28 23:36 UTC, coliff commented on content/en/hosting-and-deployment/hosting-on-firebase.md
> +Dont forget to update your static pages before push!
Don't

2021-03-04 07:09 UTC, coliff commented on content/en/hosting-and-deployment/hosting-on-firebase.md
> +Firebase script with retrive credentials, create a service account you can later manage in yout github settings.
should be 'manage in your GitHub'

2021-03-08 12:00 UTC, coliff requested changes
Thanks for the PR. Please check the spelling and fix any capitalization issues. (e.g. Firebase and GitHub should be capitalized like that)

2022-09-10 14:58 UTC, bep commented
@bggo is this still on your ... agenda (re @coliff 's remarks above)?

2022-11-13 04:34 UTC, merged