Making shortcode templates more readable by fixing spaces in parentheses
gohugoio/hugoDocs pull request #1467
Opened 2021-05-31 13:13 UTC by whs-dot-hk

2021-06-29 15:57 UTC, jmooring requested changes

2021-06-29 15:57 UTC, jmooring commented on content/en/templates/shortcode-templates.md
> +{{ with .Get "class" }} class="{{.}}"{{ end }}
```suggestion
{{ with .Get "class" }} class="{{ . }}"{{ end }}
```

2021-06-29 15:57 UTC, jmooring commented on content/en/templates/shortcode-templates.md
> +{{ if or (.Get "title") (.Get "alt") }} alt="{{ with .Get "alt" }}{{.}}{{ else }}{{ .Get "title" }}{{ end }}"{{ end }}
```suggestion
{{ if or (.Get "title") (.Get "alt") }} alt="{{ with .Get "alt" }}{{ . }}{{ else }}{{ .Get "title" }}{{ end }}"{{ end }}
```

2021-06-29 15:57 UTC, jmooring commented on content/en/templates/shortcode-templates.md
> +    {{ with .Get "link" }}<a href="{{.}}">{{ end }}
```suggestion
    {{ with .Get "link" }}<a href="{{ . }}">{{ end }}
```

2021-06-29 15:57 UTC, jmooring commented on content/en/templates/shortcode-templates.md
> +        <img src="{{ .Get "src" }}" {{ if or (.Get "alt") (.Get "caption") }}alt="{{ with .Get "alt" }}{{.}}{{ else }}{{ .Get "caption" }}{{ end }}"{{ end }} />
```suggestion
        <img src="{{ .Get "src" }}" {{ if or (.Get "alt") (.Get "caption") }}alt="{{ with .Get "alt" }}{{ . }}{{ else }}{{ .Get "caption" }}{{ end }}"{{ end }} />
```

2021-06-29 15:57 UTC, jmooring commented on content/en/templates/shortcode-templates.md
> +        {{ with .Get "attrlink" }}<a href="{{.}}"> {{ end }}
```suggestion
        {{ with .Get "attrlink" }}<a href="{{ . }}"> {{ end }}
```

2021-06-30 00:35 UTC, whs-dot-hk commented
@jmooring Thanks

2021-06-30 13:18 UTC, jmooring approved these changes

2021-06-30 13:26 UTC, merged