External resources
gohugoio/hugoDocs pull request #1569
Opened 2021-11-05 07:20 UTC by sean-pwd

Add youtube playlist to external resources page.

2021-11-06 18:58 UTC, jmooring requested changes
The addition of the video playlist is welcome.

The addition of hugo-svg-font was rejected by the project lead in https://github.com/gohugoio/hugoDocs/pull/1567/.

2021-11-06 18:58 UTC, jmooring commented on content/en/getting-started/external-learning-resources/index.md
> +### Video Playlist by Sean Emerson of Future Web Design
```suggestion
### Video Playlist by Sean Emerson
```

2021-11-06 18:58 UTC, jmooring commented on content/en/tools/other.md
> +* [hugo-svg-font](https://github.com/future-wd/hugo-svg-font) A partial & shortcode for using SVG files just like svg fonts, but without the CSS overhead.
```suggestion
```

2021-11-07 00:40 UTC, coliff approved these changes

2021-11-28 19:52 UTC, jmooring commented
Requested changes not made. Closing.

2021-11-28 19:52 UTC, closed without merging