Add urlquery function docs
gohugoio/hugoDocs pull request #1633
Opened 2022-01-18 13:43 UTC by schnerring

Fixes #1627

2022-11-07 04:33 UTC, jmooring requested changes

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +description: Takes one or more string inputs and returns a single percent-encoded string which is safe to use inside a URL query.
```suggestion
description: Returns the escaped value of the textual representation of its arguments in a form suitable for embedding in a URL query.
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +`urlquery` takes one or more string inputs and returns a single [percent-encoded](https://en.wikipedia.org/wiki/Percent-encoding) string which is safe to use inside a URL query.
```suggestion
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +The following examples create a social sharing link for Facebook.
```suggestion
This template code:
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +<a href="https://www.facebook.com/sharer.php?u={{ urlquery "https://gohugo.io/" }}">Share</a>
```suggestion
{{ $u := urlquery "https://" "example.com" | safeURL }}
<a href="https://example.org?url={{ $u }}">Link</a>
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +
```suggestion
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +<a href="https://www.facebook.com/sharer.php?u={{ urlquery "https://" "go" "hugo" ".io/" }}">Share</a>
```suggestion
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +Both of these examples render the following HTML:
```suggestion
Is rendered to:
```

2022-11-07 04:33 UTC, jmooring commented on content/en/functions/urlquery.md
> +<a href="https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgohugo.io%2F">Share</a>
```suggestion
<a href="https://example.org?url=https%3A%2F%2Fexample.com">Link</a>
```

2022-11-10 20:16 UTC, merged

2022-11-10 20:25 UTC, schnerring commented
Sorry, I kinda couldn't decipher the suggested changes you made. It would nice if GitHub supported a combined overview the suggested changes to make this easier.