Update faq.md
gohugoio/hugoDocs pull request #1763
Opened 2022-06-19 22:43 UTC by stullesha

2022-07-07 23:47 UTC, stullesha reviewed
change cron job link

2022-11-07 06:52 UTC, jmooring requested changes

2022-11-07 06:52 UTC, jmooring commented on content/en/troubleshooting/faq.md
> +* If your site is hosted on a service similar to [Netlify](https://www.netlify.com/) you can--
```suggestion
* If your site is hosted on a service similar to [Netlify](https://www.netlify.com/) you can:
```

2022-11-07 06:52 UTC, jmooring commented on content/en/troubleshooting/faq.md
> +  * use a service such as [ifttt](https://ifttt.com/date_and_time) to schedule the updates.
```suggestion
  * Use a service such as [ifttt](https://ifttt.com/date_and_time) to schedule the updates
```

2022-11-07 06:52 UTC, jmooring commented on content/en/troubleshooting/faq.md
> +  * set up a deploy hook which you can run with a cron service to deploy your site at intervals, such as [cron-job.org](https://cron-job.org/). (Netlify and Cloudflare Pages support deploy hooks).
```suggestion
  * Set up a deploy hook which you can run with a cron service to deploy your site at intervals, such as [cron-job.org](https://cron-job.org/) (both Netlify and Cloudflare Pages support deploy hooks)
```

2022-11-11 05:42 UTC, merged