docs: Update quick start to clarify the need of extended version
gohugoio/hugoDocs pull request #1828
Opened 2022-10-02 06:29 UTC by thewheat

The current theme requires the extended version of Hugo. Add extra mention of this requirement and how to check it

Fixes: #1549

**Preview of change**

<img width="795" alt="image" src="https://user-images.githubusercontent.com/892961/193441104-7e3c1534-bd9b-4197-accd-c8d4f568367c.png">

2022-10-19 16:10 UTC, coliff approved these changes

2022-10-20 16:08 UTC, jmooring requested changes

2022-10-20 16:08 UTC, jmooring commented on content/en/getting-started/quick-start.md
> +Install the **extended version of Hugo** (this is required for the current theme used)
```suggestion
Install the **extended version of Hugo** (this is required for the current theme used).
```

2022-10-20 16:08 UTC, jmooring commented on content/en/getting-started/quick-start.md
> +It should state that it is `extended`. If it does not, uninstall it and try another installation method
```suggestion
It should state that it is `extended`. If it does not, uninstall it and try another installation method.
```

2022-10-20 16:12 UTC, merged