Resource methods: add signatures, minor improvements
gohugoio/hugoDocs pull request #2017
Opened 2023-03-21 12:07 UTC by deining

This PR improves the documentation of hugo pipes by adding method signatures for the available `resources.nn` functions. It also comes with minor textual  improvements.

2023-03-21 16:53 UTC, jmooring requested changes
Thanks for this. In addition to the minor changes I have requested, I have two other comments:

1) The first heading on some of the pages is `### Usage`. It may look better to have a smaller font size, but it we enable a multilevel TOC (H2, H3, etc.) the structure will be wrong.

2) I understand why you changed the page titles, but when I click on **Asset Bundling** in the sidebar, the page title is **Concat**. That makes sense, but was unexpected. So we have a mismatch between titles, link titles, and URLs.

There's some prep work underway for a new reference, where functions are name-spaced. Although not template functions, per se, perhaps we can group all of the resource.Foo methods in one place. It's on my list.

2023-03-21 16:53 UTC, jmooring commented on content/en/hugo-pipes/postcss.md
> +### Usage
```suggestion
```

2023-03-21 16:53 UTC, jmooring commented on content/en/hugo-pipes/postcss.md
> +
```suggestion
```

2023-03-21 16:53 UTC, jmooring commented on content/en/hugo-pipes/transform-to-css.md
> +description: Transformes an Sass or SCSS file into a CSS file.
```suggestion
description: Transpile Sass to CSS.
```

2023-03-21 16:53 UTC, jmooring commented on content/en/hugo-pipes/transform-to-css.md
> +linkTitle: Transform Sass / SCSS
```suggestion
linkTitle: Transpile Sass to CSS
```

2023-03-21 17:09 UTC, deining commented on content/en/hugo-pipes/postcss.md
> +### Usage
Removed the line as requested.

2023-03-21 17:09 UTC, deining commented on content/en/hugo-pipes/postcss.md
> +
Removed the line as requested.

2023-03-21 17:09 UTC, deining commented on content/en/hugo-pipes/transform-to-css.md
> +description: Transformes an Sass or SCSS file into a CSS file.
Changed as requested.

2023-03-21 17:09 UTC, deining commented on content/en/hugo-pipes/transform-to-css.md
> +linkTitle: Transform Sass / SCSS
Changed as requested.

2023-03-21 17:13 UTC, deining commented
> Thanks for this. In addition to the minor changes I have requested, I have two other comments:
> 
>     1. The first heading on some of the pages is `### Usage`. It may look better to have a smaller font size, but it we enable a multilevel TOC (H2, H3, etc.) the structure will be wrong.

I see. I chose `###` in all cases since the small font size looks better.

>     2. I understand why you changed the page titles, but when I click on **Asset Bundling** in the sidebar, the page title is **Concat**. That makes sense, but was unexpected. So we have a mismatch between titles, link titles, and URLs.

I changed the link title to `Concatenating assets` so that link title and title are more similar.
 
> There's some prep work underway for a new reference, where functions are name-spaced. Although not template functions, per se, perhaps we can group all of the resource.Foo methods in one place. It's on my list.

Thanks for your continued documentation efforts!

2023-03-23 18:04 UTC, jmooring commented
> The first heading on some of the pages is `### Usage`. It may look better to have a smaller font size, but it we enable a multilevel TOC (H2, H3, etc.) the structure will be wrong.

Start with H2.

2023-03-23 22:26 UTC, deining commented
> > The first heading on some of the pages is `### Usage`. It may look better to have a smaller font size, but it we enable a multilevel TOC (H2, H3, etc.) the structure will be wrong.
> 
> Start with H2.

Done.

2023-03-24 03:49 UTC, merged