Provide an example of how to update the base URL for GitLab
gohugoio/hugoDocs pull request #2801
Opened 2024-12-27 05:52 UTC by alecthegeek

Add an example CI/CD script fragment to configure the GitLab pages URL

2024-12-27 17:40 UTC, jmooring commented
Why can't we just pass `CI_PAGES_URL` to the `--baseURL` command line flag?

2024-12-28 22:07 UTC, alecthegeek commented
> Why can't we just pass `CI_PAGES_URL` to the `--baseURL` command line flag?

And this is the difference between the merely competent amateur and the very export professional. 😄 

Change done. Now I need to go update my projects...

2025-01-03 20:45 UTC, deining requested changes

2025-01-03 20:45 UTC, deining commented on content/en/hosting-and-deployment/hosting-on-gitlab.md
> +A consistent way to acheive this is by using the --baseURL option to the Hugo generate command.
Typo: `acheive` -> `achieve`

2025-01-03 20:50 UTC, jmooring commented
Yeah, let's hold off on this. Some more testing is required, but we probably just want to change the build command in the example. No need to add a paragraph describing this.

2025-01-04 16:43 UTC, closed without merging

2025-01-04 16:52 UTC, jmooring commented
@alecthegeek 

Thanks for letting us know about the GitLab environment variable. I've update the example workflow file to pass this variable to the build command; there is no need to document its use (i.e., it's self-documenting). I did not remove the following:

![image](https://github.com/user-attachments/assets/2be01d96-309e-44da-81e7-3eb4e90918b6)

Why? Because it's important to locally test (i.e., `hugo server`) how your site is served when server from a subdirectory.